### ISSUE TITLE
Compressed text in markdown quote

### ISSUE THREAD

**Issue by shoesforindustry** [iksi/kirby-compress#13]
Using the text below: [from this URL](http://susanhall.shoesforindustry.net/articles/munro-v-jenkins-a-tale-of-two-tweets)

> “condoned and approved of   the   fact   that   in   the   course   of   an anti-government   protest   there   had   been   vandalisation  by  obscene  graffiti  of  the  women’s  war  memorial  in  Whitehall, a  monument to those who fought for her freedom.”

With compress it looks like this:

<img width="784" alt="screen shot 2017-04-05 at 09 09 14" src="https://cloud.githubusercontent.com/assets/2102743/24695981/c48dbf2a-19df-11e7-8bf0-3c17e13f7f78.png">

Without:

<img width="679" alt="screen shot 2017-04-05 at 09 09 37" src="https://cloud.githubusercontent.com/assets/2102743/24695992/d01b43d0-19df-11e7-9b80-d9184ef5eddb.png">

Any Ideas?

**Comment by iksi** [comment]
Basically the same issue as #14 where multiple consecutive spaces are removed. The quote you’re using actually contains multiple spaces between certain words which you can see by looking at the source. I’m looking into it.

**Comment by iksi** [comment]
It’s trucky to see wheter multiple whitespace are intentional or not, so I chose to replace whitespace with one space so this won’t happen.
